### PR TITLE
Missing property for writable stack trace in bulk config properties

### PR DESCRIPTION
**Pull request by worldtiki**
Missing property for writable stack trace in bulk config properties

### CODE REVIEW

**Review by fabianpiau — APPROVED** [review]

**Review by RobWin — APPROVED** [review]

**Comment by RobWin** [comment]
> This branch cannot be rebased due to conflicts

Strange.

**Review by ffeltrinelli — APPROVED** [review]

**Comment by worldtiki** [comment]
> > This branch cannot be rebased due to conflicts
> 
> Strange.

I started from a really old revision of my fork. Do you want me to close this pr and open a new one from scratch?

**Comment by RobWin** [comment]
Yes please. I can't see why there are conflicts.

**Comment by worldtiki** [comment]
Closing in favor of #1159

**Pull request closed without merging**
