### PR TITLE
Issue #936: Reusing MDC in FallbackMethod

### PR DESCRIPTION
**Pull request by razum90**
Pull request for issue #936.

Currently when the `invoke()` method in `FallbackMethod` is called the MDC is lost (that was present when calling the original method). Expected behaviour, at least from my personal point of view, is that the same MDC present when calling the original method, should also be present when the fallback method is invoked. One use-case for this is to be able to track the call-chain in a service through logs, including the fallback method invocation, using a request-id for example present in the MDC.

This is the behaviour I've tried to implement in this pull request. I also added the `withMdcContextMap()` method inside the `FallbackMethod` class, to be able to control what MDC should be used when invoking, in case, for any reason, one would not want the current MDC (present when calling the original method) to be used. But since that's not used, and I don't really see a use-case for it, maybe it should be removed. Let me know what you think.

### CODE REVIEW

**Comment by razum90** [comment]
The build seems to be failing in master, for the same reason this build is failing, by the way.

**Comment by RobWin** [comment]
I wonder if it works. The fallback method is currently invoked in the same Thread like the protected method.
Why is the MDC context lost from the Threadlocal.
Do you also use a ThreadPoolBulkhead on your method as well?

**Comment by razum90** [comment]
@RobWin Yes, we are.

This is what it looks like:

```
@Bulkhead(name = "name", type = Bulkhead.Type.THREADPOOL)
@TimeLimiter(name = "name")
@CircuitBreaker(name = "name", fallbackMethod = "fallback")
public CompletableFuture<String> asyncCheck(String arg) {
    return CompletableFuture.supplyAsync(MDCUtil.withMdc(() -> client.execute(arg)));
}

public CompletableFuture<String> fallback(String arg, Exception exception) {
    log.error("...", exception);
    return CompletableFuture.completedFuture("response");
}
```

**Comment by RobWin** [comment]
Sry, your code is wrong. Bulkhead already executes your method code inside a thread. You should not call `supplyAsync` and spawn another thread. Just return `CompletableFuture.completedFuture()` like in your fallback method.

**Comment by razum90** [comment]
Ah, yep. Thanks, will change according to your suggestion. However should not change the fact that the MDC is empty in the fallback method right?

**Comment by RobWin** [comment]
It should, because the fallback should be invoked in the same thread than the original method.

**Comment by razum90** [comment]
Did you try it? I did, and the MDC was still empty for me. But maybe I missed something.

**Comment by RobWin** [comment]
I will retest it, but today I'm on vacation. But if you can quickly test it, I'm happy to read your feedback.

**Comment by RobWin** [comment]
What is your MDC util doing? Is the MDC also in the asyncCheck method empty? Did you configure a ContextPropagator?

**Comment by razum90** [comment]
I did try it again, and the MDC is still empty in the fallback. I can see the fallback is not executed in the same thread as asyncCheck:

asyncCheck thread name: bulkhead-name-2
fallback thread name: pool-3-thread-1

**Comment by razum90** [comment]
I'm not calling the MDC util method anymore after I removed the supplyAsync call according to your suggestions. The MDC is populated in the asyncCheck method. Yes, I had a look and we are using a ContextPropagator, looks like this:

`
public class DefaultContextPropagator implements ContextPropagator<Map> {

    @Override
    public Supplier<Optional<Map>> retrieve() {
        return () -> (Optional) Optional.ofNullable(MDC.getCopyOfContextMap());
    }

    @Override
    public Consumer<Optional<Map>> copy() {
        return (t) -> t.ifPresent(e -> {
            if (MDC.getCopyOfContextMap() != null) {
                MDC.clear();
            }
            MDC.setContextMap(e);
        });
    }

    @Override
    public Consumer<Optional<Map>> clear() {
        return (t) -> {
            if (MDC.getCopyOfContextMap() != null) {
                MDC.clear();
            }
        };
    }
}
`

If I remove the usage of that, the MDC is also empty in the asyncCheck method.

**Comment by RobWin** [comment]
We have to debug https://github.com/resilience4j/resilience4j/blob/master/resilience4j-spring/src/main/java/io/github/resilience4j/fallback/CompletionStageFallbackDecorator.java

**Comment by razum90** [comment]
@RobWin Seems to be the TimeLimiter spawning a new thread for the fallback to run in, at https://github.com/resilience4j/resilience4j/blob/master/resilience4j-timelimiter/src/main/java/io/github/resilience4j/timelimiter/internal/TimeLimiterImpl.java#L184

**Comment by RobWin** [comment]
Ah! You are using the timelimiter as well. Didn't know that the fallback method was handling a timeout exception in your case.

**Comment by RobWin** [comment]
Yes, here we need to propagate the Thread Context

**Comment by razum90** [comment]
Ah I see, using the context propagator? If so, how should we go about and structure it? I see it's now only a part of thread-pool-bulkhead

**Comment by RobWin** [comment]
Yes, I guess we need to add the support for context propagator also to the TimeLimiter component.

**Comment by razum90** [comment]
I agree. I guess it would be nice only having to pointing out once which context propagator to use, instead of in both in the thread-pool-bulkhead + timelimiter module. Or do you see a case where you would want to use different context propagators for them?

**Comment by razum90** [comment]
Hey @RobWin, how should we proceed with this? Do you guys have plans on fixing this yourselves or should I spend some time on it?

**Comment by RobWin** [comment]
We are disucssing it internally ... ironically right at this moment,

**Comment by RobWin** [comment]
Currently we are investigating, if our `ThreadPoolBulkhead` could implement `ScheduledExecutorService`  and also used by TimeLimiter/Retry to schedule retry attempts or TimeoutExceptions.

**Comment by razum90** [comment]
Hi @RobWin, did you come to a conclusion with the investigation?

**Comment by RobWin** [comment]
Yes, we are working on this PR -> https://github.com/resilience4j/resilience4j/pull/1204

**Pull request closed without merging**
