### PR TITLE
Springboot2 sse vrbranch

### PR DESCRIPTION
**Pull request by vijaycse**

### CODE REVIEW

**Comment by vijaycse** [comment]
To unblock other folks, I made a temp fix here @RobWin  , Please see if this makes sense

**Comment by vijaycse** [comment]
never mind..

**Comment by vijaycse** [comment]
this is also failing.  running fine locally. looking at it..

**Comment by RobWin** [comment]
Could you please close master again and do you changes on master. This PR contains a lot of other commits?

**Comment by vijaycse** [comment]
ohh ya. thats my laziness

**Pull request closed without merging**
