### PR TITLE
#174 Dynamic ratelimiter configuration

### PR DESCRIPTION
**Pull request by storozhukBM**

### CODE REVIEW

**Comment by storozhukBM** [comment]
Hi @RobWin 
I'm also concerned about it, but unfortunately I haven't found the way to make it safe from the API stand point. Due to the following: 
`rateLimiter.getRateLimiterConfig().updateTimeoutDuration(...)` - I think we want to keep config immutable for cases when it have been reused 
across different rate limiters, we should change behavior of only one of them.
`rateLimiter.updateRateLimiterConfig(RateLimiterConfig config)` - we should not allow to change limit refresh period, so we can't accept completely new config.

**Comment by RobWin** [comment]
Ok.
`rateLimiter.getRateLimiterConfig().updateTimeoutDuration(...)` could create a new instance of the rateLimiterConfig internally.

**Comment by RobWin** [comment]
But you mean I could be confusing, because people think you can modify an existing RateLimiterConfig?

**Comment by storozhukBM** [comment]
rateLimiter.getRateLimiterConfig() should return configuration. like that
```java
RateLimiterConfig oldConfig = rateLimiter.getRateLimiterConfig();
```
Let's assume `updateTimeoutDuration(...)` method will produce new config without changing previous
```java
RateLimiterConfig newConfig = oldConfig.updateTimeoutDuration(...)
```
But then we should insert this new config to the rateLimiter which is actually your second variant
`rateLimiter.updateRateLimiterConfig(RateLimiterConfig config)` where we can't be sure that user changed only allowed options. 
And runtime checks for such disallowed changes aren't very convenient.

**Comment by RobWin** [comment]
OK then lets keep your solution

**Comment by storozhukBM** [comment]
Thank you

**Pull request merged**
