### PR TITLE
Add osgi support

### PR DESCRIPTION
**Pull request by cpilsworth**
This PR implements #47 

This generates the OSGi META-INF/MANIFEST.MF file that decribes the jar as an OSGi bundle.

See https://docs.gradle.org/current/userguide/osgi_plugin.html

The library depends upon `javaslang` & `slf4j`, which both seems to be an [OSGi bundle]:(https://github.com/javaslang/javaslang/blob/master/pom.xml#L271-L284)
```
javaslang.collection,version=[2.0,3) from io.javaslang (482)
javaslang.control,version=[2.0,3) from io.javaslang (482)
org.slf4j,version=[1.7,2) from slf4j.api (17)
```

It also has the following dependencies which it expects to import - I wanted to check whether the following dependencies could be considered _optional_ - only required for certain features?
```
io.reactivex,version=[2.0,3) -- Cannot be resolved
io.reactivex.disposables,version=[2.0,3) -- Cannot be resolved
io.reactivex.functions,version=[2.0,3) -- Cannot be resolved
io.reactivex.processors,version=[2.0,3) -- Cannot be resolved
javax.cache,version=[1.0,2) -- Cannot be resolved
org.reactivestreams,version=[1.0,2) -- Cannot be resolved
```

### CODE REVIEW

**Comment by cpilsworth** [comment]
Judging by the docs support for RxJava and JCache is optional - people may choose not to use that functionality - so making those dependencies optional.  Let me know if this isn't right.

**Comment by RobWin** [comment]
Hi, unfortunately RxJava is not optional at the moment.
We should have a look at it again, after we have modularized the project. 
The new home of the project will be: https://github.com/resilience4j

**Comment by RobWin** [comment]
Good work so far :)  :+1:

**Comment by cpilsworth** [comment]
Thanks.  The OSGi integration test loads the generated bundle from the gradle build folder - this works locally, but not on travis it seems.  Need to work out why.

**Comment by cpilsworth** [comment]
@RobWin I think this is at a good point - let me know what you think.  

I could have the osgi loading test verify all of the packages, but it might cause you more problems if you are planning to modularise anyway.  If I can be any help in modularising so it does not have a hard dependency on rxjava etc, then let me know.

**Comment by RobWin** [comment]
Thx for your effort. I  have a look at it next week.

**Comment by storozhukBM** [comment]
Hey @cpilsworth,
This is really great work, thank you. I'll try to use it as example for all modules.

**Comment by david-t-daniel** [comment]
@cpilsworth I can see the manifest is generated correctly.  The unit test is not passing for me when I do a build from the command line.  The normal way I do integration tests is by including the test class in the jar itself and then specifying the test class in the manifest file http://bnd.bndtools.org/chapters/310-testing.html.  I can also see how including integration tests in the jar is undesirable though.  I was not able to figure out how to use gradle with eclipse to run the tests but I can run them from the command line and will see if I can figure out why things are not working for me.

**Comment by cpilsworth** [comment]
The unit test is an integration test really, it relies upon the jar having being generated, which it then loads.  Travis has been executing `./gradlew clean check jar allTests -x test`.  I should probably indicated this as a (post-build) integration test _or_ load bundle from the build classpath rather than the jar artefact.

I've not used the test method that you've referenced before.  I've not had a chance to read through the document in detail, but it does seems strange that it would be tested from the inside.  Part of what is being tested if the external interface being presented (e.g. packages/classes exported).

**Comment by RobWin** [comment]
Hi, do you think we can start another try to OSGIfy Resilience4j?

**Comment by david-t-daniel** [comment]
The patch worked for me and generated the headers correctly it was just a unit test thing.   I can try and take a look at getting the unit test running for me but if it works for you and Chris then I am good with a merge.

**Comment by RobWin** [comment]
Yes, but we did a major refactoring and the branch cannot be merged anymore.

**Comment by david-t-daniel** [comment]
I used Chris' technique for modifying the build.gradle file and verified that it works at the individual project level.  In 2 weeks during our cleanup sprint I will update our code to vavr from javaslang and make sure working headers are in the circuitbreaker and other projects we use.  Thenk you Chris for this work again.

**Comment by cpilsworth** [comment]
Sorry, I've not found the time to update this since the project was split into modules.  There's been a lot of activity on the project since I looked at this!  

Not sure if it's still an issue, but at one time a couple of the modules shared a common base package - this could cause problems with multiple bundles exporting the same package.

**Pull request closed without merging**
