### PR TITLE
upgrade to reactor 3.4.0

### PR DESCRIPTION
**Pull request by piyushmor**
- Upgrades project reactor to 3.4.0
- fixes issue #1233 with the new retry mechanism for reactor 3.4.0

### CODE REVIEW

**Comment by RobWin** [comment]
Some tests failed now:

```
io.github.resilience4j.circuitbreaker.monitoring.events.CircuitBreakerStreamEventsTest > streamAllEvents FAILED
    java.lang.NoSuchMethodError at CircuitBreakerStreamEventsTest.java:111
io.github.resilience4j.circuitbreaker.monitoring.events.CircuitBreakerStreamEventsTest > streamEventsbyName FAILED
    java.lang.NoSuchMethodError at CircuitBreakerStreamEventsTest.java:111
io.github.resilience4j.circuitbreaker.monitoring.events.CircuitBreakerStreamEventsTest > streamEventsbyNameAndType FAILED
    java.lang.NoSuchMethodError at CircuitBreakerStreamEventsTest.java:111
io.github.resilience4j.circuitbreaker.monitoring.events.CircuitBreakerHystrixStreamEventsTest > streamAllEvents FAILED
    java.lang.NoSuchMethodError at CircuitBreakerHystrixStreamEventsTest.java:112
io.github.resilience4j.circuitbreaker.monitoring.events.CircuitBreakerHystrixStreamEventsTest > streamEventsbyName FAILED
    java.lang.NoSuchMethodError at CircuitBreakerHystrixStreamEventsTest.java:112
```

**Comment by RobWin** [comment]
I will have a look at it. We might have to upgrade Spring Boot to 2.4.0 as well

**Comment by RobWin** [comment]
There are more changes in 2.4.0 :(
`org.springframework.boot.actuate.autoconfigure.health.HealthIndicatorAutoConfiguration` does not exist anymore

**Comment by RobWin** [comment]
Next exception:

```
 java.lang.ClassNotFoundException: org.springframework.boot.context.properties.ConfigurationBeanFactoryMetadata
```

**Comment by RobWin** [comment]
Seems there is no Spring Cloud compatible verion for Spring Boot 2.4.0 yet-

**Comment by kibantony** [comment]
> Seems there is no Spring Cloud compatible version for Spring Boot 2.4.0 yet.
> 
> Hoxton.SR9 does not seem to work.

You have to use Spring Cloud 2020.0.x aka Ilford. They are at version M6 now, I believe. See https://github.com/spring-cloud/spring-cloud-release/wiki/Spring-Cloud-2020.0-Release-Notes

**Comment by piyushmor** [comment]
spring-projects/spring-cloud#77

**Comment by magnus-larsson** [comment]
I have tried out the merge request from @piyushmor and after changing `HealthIndicatorAutoConfiguration` to `HealthContributorAutoConfiguration` (as described in the deprecation note in JavaDoc) everything compiles without any errors.

I have tried the local build with my use cases of Resilience4J (CircuitBreaker and Retry) together with the GA release of Spring Cloud 2020.0.0 and it works fine.

Unfortunately, I can't get the Resilience4J tests to run in a reproducible way on my Mac, `./gradlew test` fails on different tests each time I run it. Maybe some problem in my environment.

Maybe there is not much more work needed before Resilience4J can run on Reactor 3.4.0 (required by Spring Cloud 2020.0.0)?

**Comment by joschi** [comment]
> Unfortunately, I can't get the Resilience4J tests to run in a reproducible way on my Mac, `./gradlew test` fails on different tests each time I run it. Maybe some problem in my environment.

I had the same problems on my Mac.

Maybe the changes from https://github.com/resilience4j/resilience4j/pull/1286 could help?

**Comment by piyushmor** [comment]
> > Unfortunately, I can't get the Resilience4J tests to run in a reproducible way on my Mac, `./gradlew test` fails on different tests each time I run it. Maybe some problem in my environment.
> 
> @magnus-larsson I had the same problems on my Mac.
> 
> Maybe the changes from #1286 could help?

seems like the build passed without it :)

**Comment by magnus-larsson** [comment]
Thanks, @piyushmor and @joschi!

Yes, the Gradle retry mechanism described in #1286 helped me to run all tests successfully on my Mac!

Is the any more work required on this issue?

**Comment by RobWin** [comment]
Yes, we might need to identify the flaky tests and fix them in a separate PR.
We should not add a workaround, but fix the tests instead.

**Comment by magnus-larsson** [comment]
Great, thanks!

Is there a snapshot build available that I can try out?

**Comment by joschi** [comment]
> Yes, we should identify the flaky tests and fix them in a separate PR.
> We should not add a workaround, but fix the tests instead.

The changes in #1286 could help with that with a small change (to eventually fail the build after identifying flaky tests).

**Comment by RobWin** [comment]
@magnus-larsson: https://oss.jfrog.org/oss-snapshot-local/io/github/resilience4j
You can use `1.7.0-SNAPSHOT`.

https://resilience4j.readme.io/docs/gradle#snapshot

https://resilience4j.readme.io/docs/comparison-to-netflix-hystrix-1#snapshot

**Comment by magnus-larsson** [comment]
@RobWin: Thank you, the `1.7.0-SNAPSHOT` worked fine for my use cases!

Do you have any tentative date for a 1.7.0 release?

**Pull request merged**
