### PR TITLE
adding retry method annotation, closes #91

### LINKED ISSUE #91: Ratpack support for retry method interceptor
Just like `@CircuitBreaker` and `@RateLimiter`.

### PR DESCRIPTION
**Pull request by drmaas**
also:

* adds methods to retry registry to ensure concurrent isolation where needed

### CODE REVIEW

**Comment by drmaas** [comment]
@RobWin let me know if the completionstage stuff should be refactored here or in a separate issue. Currently the tests pass, but they may be 'off by 1' if the circuitbreaker check happens after the completionstage has already executed.

**Comment by RobWin** [comment]
I think we should disable CompletionStage interception and then merge the PR. We can find a solution in a separate issue..

**Comment by drmaas** [comment]
See #95 for the remaing work to be done for CompletionStage.

**Comment by drmaas** [comment]
@RobWin PTAL

**Pull request merged**
