### PR TITLE
Issue #1452: base config's exceptionPredicate should be null, when exceptions are instance-specific.

### LINKED ISSUE #1452: All exceptions are counted toward failure when record-exceptions is instance-specific
Resilience4j version: 1.7.0

Java version: 1.8.0_292

When I don't define `record-exceptions` in the base config but do so under instance, the instance-specific config is not honored and all exceptions are counted toward failure rate.

Code to reproduce is here: https://github.com/hoathaivu/resilience4j-spring-boot2-demo

The code was forked from demo and minor changes were applied, most notably the config change:

image

When a call was made to `/backendA/ignore` endpoint, I got below log:

> 2021-06-03 19:09:19.503  INFO 1294293 --- [or-http-epoll-2] io.github.robwin.Application             : 2021-06-03T19:09:19.503-04:00[America/Detroit]: CircuitBreaker 'backendA' recorded an error: 'io.github.robwin.exception.BusinessException: This exception should ignored by the CircuitBreaker of backend A'. Elapsed time: 4 ms
2021-06-03 19:09:19.505  INFO 1294293 --- [or-http-epoll-2] io.github.robwin.Application             : 2021-06-03T19:09:19.505-04:00[America/Detroit]: CircuitBreaker 'backendA' exceeded failure rate threshold. Current failure rate: 100.0
2021-06-03 19:09:19.508  INFO 1294293 --- [or-http-epoll-2] io.github.robwin.Application             : 2021-06-03T19:09:19.507-04:00[America/Detroit]: CircuitBreaker 'backendA' changed state from CLOSED to OPEN

When I tried to debug, it seems to be because how instance configuration is created (related code is [here](https://github.com/resilience4j/resilience4j/blob/master/resilience4j-framework-common/src/main/java/io/github/resilience4j/common/circuitbreaker/configuration/CircuitBreakerConfigurationProperties.java#L70) and [here](https://github.com/resilience4j/resilience4j/blob/master/resilience4j-circuitbreaker/src/main/java/io/github/resilience4j/circuitbreaker/CircuitBreakerConfig.java#L783)). Basically, default behavior (always record exception) is merged with instance-specific behavior (record only a specific exception) using `or`, so the end result is the default behavior.

### PR DESCRIPTION
**Pull request by melochin**
fix #1452

### CODE REVIEW

**Comment by melochin** [comment]
Unit test is failed, but the test is passed in my local environment. The test result may not be stable.
```
io.github.resilience4j.bulkhead.ThreadPoolBulkheadTest > shouldExecuteRunnableAndFailWithBulkHeadFull FAILED
    java.lang.AssertionError at ThreadPoolBulkheadTest.java:93
```

**Comment by RobWin** [comment]
```
CircuitBreakerRegistrySpec > backend-b configuration FAILED
    org.spockframework.runtime.ConditionNotSatisfiedError at CircuitBreakerRegistrySpec.groovy:84
 ```

**Comment by melochin** [comment]
@RobWin hi, tests are passed, please review code.

**Review by RobWin — APPROVED** [review]

**Comment by RobWin** [comment]
thx

**Pull request merged**
