### PR TITLE
Getters for waitInterval of RetryOnRetryEvent

### PR DESCRIPTION
**Pull request by slawekjaranowski**
fix: #775

### CODE REVIEW

**Comment by RobWin** [comment]
Could you please add a test to [RetryEventTest](https://github.com/resilience4j/resilience4j/blob/master/resilience4j-retry/src/test/java/io/github/resilience4j/retry/event/RetryEventTest.java) :)

**Comment by slawekjaranowski** [comment]
yes of course

**Comment by slawekjaranowski** [comment]
I see some inconsistent in `AbstractRetryEvent` field  `lastThrowable` is annotated with @ Nullable, but in child class `RetryOnSuccessEvent`, `RetryOnErrorEvent`, `RetryOnIgnoredErrorEvent` this annotation is missed  on constructor parameter.
`RetryOnRetryEvent` has @ Nullable in constructor on this field.

I can fix it - by the way

**Comment by RobWin** [comment]
Thanks

**Pull request merged**
