### PR TITLE
Improvement on race condition in cache module

### PR DESCRIPTION
**Pull request by cschubertcs**
Related to #1809.

Uses the proposed `EntryProcessor` to leverage the concurrency promisses of the underlying JCache implementation.

Before, the evaluation of the `Supplier` might happen multiple times in case of multiple threads trying to access the Cache.

### CODE REVIEW

**Comment by RobWin** [comment]
Thank you

**Comment by RobWin** [comment]
Seems some tests are failing

**Comment by cschubertcs** [comment]
Okay, wasn't aware of tests outside of the cache module relying on the cache implementation. Gonna dive into it.

**Comment by RobWin** [comment]
thank you

**Comment by RobWin** [comment]
Ready to be merged?

**Comment by cschubertcs** [comment]
From my point of view yes!

**Pull request merged**
