### PR TITLE
Removed deprecated documentation (#867)

### PR DESCRIPTION
**Pull request by hexmind**
Migrated to User Guide: https://resilience4j.readme.io/docs.

### CODE REVIEW

**Comment by rusyasoft** [comment]
@hexmind I was wondering where the retrofit usage guide will go which is currently [here](https://github.com/resilience4j/resilience4j/blob/master/resilience4j-documentation/src/docs/asciidoc/addon_guides/retrofit.adoc). I'm not sure is this usable guide or is it deprecated? Anyway, you said it is migrated to  https://resilience4j.readme.io/docs but I couldn't find it there. Could you please point it out?

**Comment by hexmind** [comment]
Don't worry, `resilience4j-documentation` will be still available at https://github.com/resilience4j/resilience4j-deprecated (https://github.com/resilience4j/resilience4j-deprecated/pull/4).
You are right, not everything was migrated. @rusyasoft  Are you interested in contribution of https://resilience4j.readme.io/docs?

**Comment by rusyasoft** [comment]
@hexmind yeah why not. Is there any agenda for docs contribution?

**Comment by Romeh** [comment]
@rusyasoft  just add ur doc contribution to https://resilience4j.readme.io/docs as suggest edits and it will be reviewed by the team and merged in between u can use the deprecated docs as a reference for retrofit documentation introduction in the new doc repo .

**Comment by hexmind** [comment]
Exactly. I have added Feign, Retrofit pages under `Add-on modules` category. @rusyasoft

**Pull request merged**
