### PR TITLE
Add response predicate to retry sync and async for enhancement #259

### PR DESCRIPTION
**Pull request by Romeh**

### CODE REVIEW

**Comment by RobWin** [comment]
Thx, LGTM. 
But  could you fix the formatting issues in the test classes. Some methods are indented.

**Comment by Romeh** [comment]
Wired i do not have the same locally in my idea ! is there any project code style rules i can import or check  ? i will check it again and see what has happend

**Comment by Romeh** [comment]
@RobWin  code style is updated for the test cases , please check and tell me if there is any other issues or concerns to cover .
Thx a lot :)

**Comment by RobWin** [comment]
Sry, I was very busy the last days.

**Pull request merged**
