### PR TITLE
bugfix in spring aspects

### PR DESCRIPTION
**Pull request by lespinsideg**
`CircuitBreakerAspect` couldn't handle `CompletionStage` returning method.

### CODE REVIEW

**Comment by lespinsideg** [comment]
I also fixed that in BulkheadAspect and RateLimiterAspect.

**Comment by Romeh** [comment]
@lespinsideg  Thx a lot for your PR as usual :). , your bug fix is already included in another PR ongoing , i will include PR reference shortly .

Thanks a lot for your bug fixing effort man ! , keep it coming please :)

**Comment by Romeh** [comment]
@lespinsideg  it is already included as well ;)

**Comment by Romeh** [comment]
here https://github.com/resilience4j/resilience4j/pull/406/files

**Comment by Romeh** [comment]
closing as it is already covered in https://github.com/resilience4j/resilience4j/pull/406/files

**Pull request closed without merging**
