### PR TITLE
adding non-coroutine kotlin wrapper functions as a convenience

### PR DESCRIPTION
**Pull request by drmaas**
@RobWin @bradnewman I didn't add any tests - let me know what kind of tests would add value, or if any other wrapper functions would be useful.

### CODE REVIEW

**Comment by RobWin** [comment]
Yes, I think the extension functions make sense.
But could you please still add some tests.

**Comment by drmaas** [comment]
Looking at why build failed

**Comment by drmaas** [comment]
@RobWin ptal when you get a change. Build is fixed.

**Comment by RobWin** [comment]
Thx

**Pull request merged**
