### PR TITLE
micronaut: cleanup

### PR DESCRIPTION
**Pull request by pollend**
I went back through my code and I'm doing another pass where I try to cleanup the code more and improve the coverage in the test. I forgot to write some basic test cases for ratelimiter, add some test cases for CircuitBreaker, and added copyright to all the files missing it. I have quite  a few spelling mistakes that I've also corrected. I should try add some more test cases to cover the configuration half. starting to look a bit cleaner.

### CODE REVIEW

**Comment by RobWin** [comment]
Please tell me when I can review it

**Comment by RobWin** [comment]
Done?

**Comment by pollend** [comment]
I need to write more test, having a bit of trouble trying to write the correct test.

**Comment by RobWin** [comment]
Just ping me if you have any questions

**Comment by pollend** [comment]
Any test cases in particular that should be covered given the spring boot tests?

**Comment by pollend** [comment]
@RobWin so micronaut uses a gradle annotation process to generate adoc. would that be relevant for documenting the configuration?

**Comment by RobWin** [comment]
What kind of AsciiDoc documentation is generated? Something like JavaDoc as AsciiDoc?
I think we can add such an endpoint at a later point in time.

**Comment by RobWin** [comment]
@pollend Would you like to join our Slack channel?

**Comment by pollend** [comment]
Sure

**Comment by RobWin** [comment]
Which email address can I use to invite you?

**Comment by pollend** [comment]
You can use my gmail

**Comment by RobWin** [comment]
Where can I find it? :)

**Comment by Romeh** [comment]
> Where can I find it? :)

i guess he meant this one  : 
Sure mpollind at gmail

**Comment by Romeh** [comment]
closing as it will be included in https://github.com/resilience4j/resilience4j/pull/1179

**Pull request closed without merging**
