### PR TITLE
Custom Prometheus buckets

### PR DESCRIPTION
**Pull request by kdombeck**
We have services that take less than 200ms and the default buckets for Prometheus are much larger than we need and causes a lot of data to be exported. By allowing a user to customize the buckets for the Histogram we can greatly reduce the amount of data exported and generate finer grained buckets at the same time.

Example of buckets currently being exported for each name/kind
```
# HELP resilience4j_circuitbreaker_calls Total number of calls by kind
# TYPE resilience4j_circuitbreaker_calls histogram
resilience4j_circuitbreaker_calls_bucket{name="myService",kind="failed",le="0.005",} 0.0
resilience4j_circuitbreaker_calls_bucket{name="myService",kind="failed",le="0.01",} 0.0
resilience4j_circuitbreaker_calls_bucket{name="myService",kind="failed",le="0.025",} 0.0
resilience4j_circuitbreaker_calls_bucket{name="myService",kind="failed",le="0.05",} 0.0
resilience4j_circuitbreaker_calls_bucket{name="myService",kind="failed",le="0.075",} 0.0
resilience4j_circuitbreaker_calls_bucket{name="myService",kind="failed",le="0.1",} 0.0
resilience4j_circuitbreaker_calls_bucket{name="myService",kind="failed",le="0.25",} 6.0
resilience4j_circuitbreaker_calls_bucket{name="myService",kind="failed",le="0.5",} 6.0
resilience4j_circuitbreaker_calls_bucket{name="myService",kind="failed",le="0.75",} 6.0
resilience4j_circuitbreaker_calls_bucket{name="myService",kind="failed",le="1.0",} 6.0
resilience4j_circuitbreaker_calls_bucket{name="myService",kind="failed",le="2.5",} 6.0
resilience4j_circuitbreaker_calls_bucket{name="myService",kind="failed",le="5.0",} 6.0
resilience4j_circuitbreaker_calls_bucket{name="myService",kind="failed",le="7.5",} 6.0
resilience4j_circuitbreaker_calls_bucket{name="myService",kind="failed",le="10.0",} 6.0
resilience4j_circuitbreaker_calls_bucket{name="myService",kind="failed",le="+Inf",} 6.0
resilience4j_circuitbreaker_calls_count{name="myService",kind="failed",} 6.0
resilience4j_circuitbreaker_calls_sum{name="myService",kind="failed",} 1.2666849999999998
resilience4j_circuitbreaker_calls_bucket{name="myService",kind="successful",le="0.005",} 0.0
resilience4j_circuitbreaker_calls_bucket{name="myService",kind="successful",le="0.01",} 0.0
resilience4j_circuitbreaker_calls_bucket{name="myService",kind="successful",le="0.025",} 0.0
resilience4j_circuitbreaker_calls_bucket{name="myService",kind="successful",le="0.05",} 6.0
resilience4j_circuitbreaker_calls_bucket{name="myService",kind="successful",le="0.075",} 6.0
resilience4j_circuitbreaker_calls_bucket{name="myService",kind="successful",le="0.1",} 11.0
resilience4j_circuitbreaker_calls_bucket{name="myService",kind="successful",le="0.25",} 14.0
resilience4j_circuitbreaker_calls_bucket{name="myService",kind="successful",le="0.5",} 14.0
resilience4j_circuitbreaker_calls_bucket{name="myService",kind="successful",le="0.75",} 14.0
resilience4j_circuitbreaker_calls_bucket{name="myService",kind="successful",le="1.0",} 14.0
resilience4j_circuitbreaker_calls_bucket{name="myService",kind="successful",le="2.5",} 14.0
resilience4j_circuitbreaker_calls_bucket{name="myService",kind="successful",le="5.0",} 14.0
resilience4j_circuitbreaker_calls_bucket{name="myService",kind="successful",le="7.5",} 14.0
resilience4j_circuitbreaker_calls_bucket{name="myService",kind="successful",le="10.0",} 14.0
resilience4j_circuitbreaker_calls_bucket{name="myService",kind="successful",le="+Inf",} 14.0
resilience4j_circuitbreaker_calls_count{name="myService",kind="successful",} 14.0
resilience4j_circuitbreaker_calls_sum{name="myService",kind="successful",} 1.092349
```

Let me know if you would rather have ```buckets``` default to ```null``` rather than the current copy/paste of the default buckets from Prometheus [Histogram](https://github.com/prometheus/client_java/blob/master/simpleclient/src/main/java/io/prometheus/client/Histogram.java#L73). If it defaults to ```null``` I could have it just not set the buckets on the Histogram when creating it, like what happens today.

### CODE REVIEW

**Comment by RobWin** [comment]
Hi,
could you also please create an issue?
Do you use Spring Boot1 or Spring Boot 2 or some other framework?

**Comment by kdombeck** [comment]
Created [issue](https://github.com/resilience4j/resilience4j/issues/701) 

For some of our micro-services we don't use Spring Boot otherwise we would use Micrometer.

For future reference do you prefer to have an issue opened up and discussed prior to a PR being created?

**Comment by RobWin** [comment]
I agree it makes sense to customize the buckets, but not via MetricNames builder. Wie need something new.

**Comment by RobWin** [comment]
Just out of interest. Which frameworks don't support Micrometer?

**Comment by kdombeck** [comment]
We are using Google Juice. It isn't so much we can't use Micrometer it is just that we currently are not.

**Comment by RobWin** [comment]
Can we change it to something like:
```
CircuitBreakerMetricsCollector.ofCircuitBreakerRegistry(
            MetricOptions.custom().histogramBuckets(new double[]{.005, .01})
                    .build(),
            circuitBreakerRegistry).register(registry);
```

**Comment by kdombeck** [comment]
Does that mean you would like to rename ```MetricNames``` to ```MetricOptions``` or add a new builder called ```MetricOptions```?

**Comment by RobWin** [comment]
Add a new builder.

**Comment by kdombeck** [comment]
Created a new builder, take a look and let me know if you see any changes I should make.

**Pull request merged**
