### PR TITLE
Adding Bulkhead metrics for Dropwizard + documentation

### PR DESCRIPTION
**Pull request by jansyk13**
Adding bulkhead metrics and documentation.

### CODE REVIEW

**Comment by storozhukBM** [comment]
Hi @jansyk13,
Thank you for this PR. I've made a brief review and it look very good so far 😄 
I'll finish the review this evening.
By the way tests failed on travis, seems you forgot to add some modules dependencies in metrics gradle file.

**Comment by jansyk13** [comment]
@storozhukBM  Thank you for the review, already fixed and pushed changes.

**Comment by jansyk13** [comment]
@storozhukBM Probably tomorrow I will make another PR introducing Bulkhead into Ratpack module, there will be more changes(finishing tests + doc)

**Comment by RobWin** [comment]
We only accept PRs of people who gave Resilience4j a star 😃

**Comment by storozhukBM** [comment]
> We only accept PRs of people who gave Resilience4j a star 😃

It was just a joke. Thank you, @jansyk13, for the effort. And of course we would love to a get star from you and here about your expirience of using Resilience4J. If you're interested in further library development we can invite you to our Slack channel where we have some small ongoing development conversations.

**Comment by RobWin** [comment]
Germans never do jokes .....
... Ok it was a joke :)

**Pull request merged**
