### PR TITLE
Support Micronaut 4

### PR DESCRIPTION
**Pull request by graemerocher**
PR contains draft of the changes to support Micronaut 4 which is JDK 17 only, so may require other changes to the build

### CODE REVIEW

**Comment by rbhambhra** [comment]
Looking forward to this - keen to move to Micronaut 4

**Comment by graemerocher** [comment]
@RobWin could you review?

**Comment by RobWin** [comment]
Thanks
Yes, when I'm back from vacation in 3 weeks.

**Comment by RobWin** [comment]
@graemerocher Thank you. Could you please add the apache header to the classes?
I don't have a script for it :(

**Comment by driverpt** [comment]
> @graemerocher Thank you. Could you please add the apache header to the classes? I don't have a script for it :(
> 
> I will then merge the PR

I recommend using [Spotless](https://github.com/diffplug/spotless)

**Comment by graemerocher** [comment]
sorry for the delay need to get further approvals from my employer

**Comment by graemerocher** [comment]
Ok got the necessary approvals, I will make the license changes and @dstepanov will need to approve

**Review by dstepanov — APPROVED** [review]

**Comment by graemerocher** [comment]
@RobWin this is now ready to be merged

**Comment by RobWin** [comment]
Thank you

**Review by RobWin — APPROVED** [review]

**Comment by graemerocher** [comment]
@RobWin Hi! Any ETA when 2.1.1 will be released?

**Comment by RobWin** [comment]
Sry, Milestone here is wrong.
It is part of the released 2.2.0

**Pull request merged**
