### PR TITLE
Add RxJava bulkhead operator for Maybe and Completable.

### PR DESCRIPTION
**Pull request by danielimre**
Added bulkhead operator support for Maybe and Completable. Part of #175
Changed some of the observers to have stricter control on how to handle disposed state.
Also, split the BulkheadOperator itself and its tests into respective classes.

### CODE REVIEW

**Comment by storozhukBM** [comment]
@danielimre please check out this Codacy report
https://www.codacy.com/app/storozhukBM/resilience4j/pullRequest?prid=1132768

**Comment by RobWin** [comment]
I like the additions, but I think the other operators (CircuitBreaker and Ratelimiter) should also support Maybe and Completable so that they are functionally identical. Would it be possible?

**Comment by danielimre** [comment]
@RobWin , I will make these changes for other operators as well. Just wanted to have a confirmation that the approach is ok. Writing RxJava operators is not trivial for me yet. Not sure if we really need that level of concurrency handling around cancellation and disposal. On the other hand, I don't think they would add too much overhead.

**Comment by RobWin** [comment]
Yes RxJava operators are not trivial

**Pull request merged**
