### PR TITLE
upgrade to spring-boot 2.2.4

### PR DESCRIPTION
**Pull request by davidkarlsen**
This change is [Reviewable](https://reviewable.io/reviews/resilience4j/resilience4j/857)

### CODE REVIEW

**Comment by RobWin** [comment]
Failed :(

**Comment by davidkarlsen** [comment]
Yes, it fails on 
```
java.lang.NoClassDefFoundError: org/eclipse/jetty/server/RequestLog$Writer
```
but that's an interface w/p any inner-class: https://git.eclipse.org/c/jetty/org.eclipse.jetty.project.git/tree/jetty-server/src/main/java/org/eclipse/jetty/server/RequestLog.java?

**Comment by davidkarlsen** [comment]
The stack-trace isn't very informative. I tried upgrading spring, micrometer, boot2, cloudcontext2 - but still same error. Any hints on what could cause this?

**Comment by RobWin** [comment]
I guess it's coming from `spring-boot-starter-test`.
Maybe it clashes with wiremock?

**Comment by RobWin** [comment]
Wiremock is using
 jetty          : '9.4.20.v20190813'

I updated to the latest wiremock version `2.26.0`, but it still fails

**Comment by RobWin** [comment]
But IntelliJ shows me something different
image

**Comment by davidkarlsen** [comment]
Also when building locally, gradle complains that 'osgi' plugin does not exist. I could not find a BUILDING/CONTRIBUTOR/DEVELOPMENT.md for guidance, and I'm no gradle whiz - this makes it a bit harder to test properly locally - I can launch tests in IntelliJ - but in the end it's the cmd line build that will measure success. I could of course just mark this PR as WIP and pump in general useful changes and see the outcome of CI. Any tips?

**Comment by RobWin** [comment]
It must be a problem with the old Jetty Version from WireMock -> https://github.com/tomakehurst/wiremock/issues/644

**Comment by RobWin** [comment]
We have to change the wiremock dependency to `com.github.tomakehurst:wiremock-jre8`

http://wiremock.org/docs/download-and-installation/

**Comment by RobWin** [comment]
Yes, that fixes the issue

**Comment by RobWin** [comment]
Closed in favor of https://github.com/resilience4j/resilience4j/pull/862

**Pull request closed without merging**
