### PR TITLE
Initial jdk11 support

### PR DESCRIPTION
**Pull request by 123Haynes**
This PR adds initial support for Java 11 aka it allows compiling resilience4j with Java 11.
This does **not** implement JPMS.

It is based on https://github.com/resilience4j/resilience4j/pull/393

### CODE REVIEW

**Comment by RobWin** [comment]
Let's not delete the jcstress files. Please only remove the gradle configuration/plugin.

**Comment by 123Haynes** [comment]
@RobWin sure. I'll restore the files in https://github.com/resilience4j/resilience4j/pull/392 and rebase https://github.com/resilience4j/resilience4j/pull/393 and this PR. 

Give me 2 minutes.

**Comment by 123Haynes** [comment]
the relevant commits are  
https://github.com/resilience4j/resilience4j/pull/397/commits/f74609f5a369d130b48c9aefc30d7ba9fd92cff7
and 
https://github.com/resilience4j/resilience4j/pull/397/commits/ac22ebeb645b29036c5b4ebde7a809122e7604ff

**Comment by RobWin** [comment]
thx

**Pull request closed without merging**
