### PR TITLE
Prepforsb23

### PR DESCRIPTION
**Pull request by davidkarlsen**
Prepare for spring-boot 2.3 by avoiding deprecated code.
Continuation of https://github.com/resilience4j/resilience4j/issues/856

---
This change is [Reviewable](https://reviewable.io/reviews/resilience4j/resilience4j/921)

### CODE REVIEW

**Comment by RobWin** [comment]
I check it tomorrow

**Comment by Romeh** [comment]
@RobWin  looks fine for me as @davidkarlsen kept the API backward compatible

**Comment by Romeh** [comment]
@davidkarlsen HealthAggregator is @deprecated since 2.2.0 in favor of {@link StatusAggregator}
it means people before spring boot 2.2.0 when they upgrade resilience4j will force them to upgrade spring boot as well  

So @RobWin  what do u think ?

**Comment by RobWin** [comment]
I think we should wait until 2.3 has been released. Users might update to the latest 2.2.X version before upgrading to 2.3.

**Comment by davidkarlsen** [comment]
@RobWin It will work with 2.2, it's just avoiding the class from 2.1, which was deprecated in 2.2 (which is the version r4j is currently at)

**Comment by davidkarlsen** [comment]
I'm fine with this going in with the SB2.3 upgrade - maybe prep a branch for it? And I guess then bump the minor version of r4j as well?

**Comment by davidkarlsen** [comment]
Would it make sense to start a branch for spring-boot 2.3 integration - to get early feedback on compatability?

**Comment by RobWin** [comment]
Yes, I think that makes sense.
But we can't deploy SNAPSHOT versions for feature branches.

**Comment by davidkarlsen** [comment]
I guess that will be 1.4.x then, and should use current milestone release of SB2.3

**Comment by davidkarlsen** [comment]
@RobWin any thoughts on this?

**Comment by RobWin** [comment]
I think 1.4 should still use Spring Boot version 2.2.6.

**Comment by davidkarlsen** [comment]
Are there features in resilience4j in stock which justifies a 1.4?
Maybe get 1.4 out with SB 2.2.6 then, and then a 1.5.x branch for SB 2.3 ?

**Comment by RobWin** [comment]
Yes, RxJava3 support and some other new features
https://github.com/resilience4j/resilience4j/milestone/29?closed=1

**Comment by davidkarlsen** [comment]
@RobWin Ready for that 1.5 branch? SB is out with their RCs now.

**Comment by davidkarlsen** [comment]
SB2.3 out now: https://github.com/spring-projects/spring-boot/releases/tag/v2.3.0.RELEASE

**Comment by davidkarlsen** [comment]
Maybe @Romeh is active on resilience4j?

**Comment by RobWin** [comment]
We are all active, but busy. It's still hard times with work a kids at home ;(

**Comment by davidkarlsen** [comment]
Awesome - any ETA on when there will be a release?

**Comment by davidkarlsen** [comment]
@RobWin @romeh Any thoughts on which release this will be in and when? Currently resilience4j is blocking us from upgrading to SB2.3.

**Comment by RobWin** [comment]
If possible I would like to include the bugfix PR also into the next release -> https://github.com/resilience4j/resilience4j/pull/997

@dlsrb6342 Only a test is missing ;)

**Pull request merged**
