### PR TITLE
Discussion #1962: Added apache commons configuration based registries bootstraping

### PR DESCRIPTION
**Pull request by deecodeme**
1. Apache commons configuration based initialization of registries. Similar to SprintBoot and Micronaut.

### CODE REVIEW

**Comment by RobWin** [comment]
Thank you.
Before I review it. Could you please add the Apache LICENSE Header to all files?
Look at the other Java Files for an example

**Comment by deecodeme** [comment]
Thanks @RobWin . I'll let you know when I'm done.

**Comment by deecodeme** [comment]
Hi @RobWin , I have added the Apache LICENSE header to all the files.

**Comment by deecodeme** [comment]
Hi @RobWin, Can you please proceed to review the changes?

**Comment by RobWin** [comment]
I'm currently on vacation. Will do it when I'm back

**Comment by deecodeme** [comment]
Hi @RobWin,

I hope you are doing well. I am just making a gentle reminder to check if you can get time to review the change?

**Review by RobWin — APPROVED** [review]

**Comment by RobWin** [comment]
Thank you

**Comment by deecodeme** [comment]
Thanks @RobWin

**Pull request merged**
