### PR TITLE
enableAutomaticTransitionFromOpenToHalfOpen in spring

### PR DESCRIPTION
**Pull request by emaas**
Add support for enableAutomaticTransitionFromOpenToHalfOpen in the spring config.
Untested because of compile issues on checkout.

### CODE REVIEW

**Comment by RobWin** [comment]
Which compile issues did you have?

**Comment by emaas** [comment]
Duplicate dependencies with different versions

**Comment by RobWin** [comment]
Interesting. Which dependencies?

**Comment by emaas** [comment]
This is what it starts with:
A conflict was found between the following modules:
    - org.slf4j:slf4j-api:1.7.24
    - org.slf4j:slf4j-api:1.6.1
  A conflict was found between the following modules:
    - org.mockito:mockito-core:2.15.0
    - org.mockito:mockito-core:2.10.0
  A conflict was found between the following modules:
    - net.bytebuddy:byte-buddy:1.7.9
    - net.bytebuddy:byte-buddy:1.7.5
  A conflict was found between the following modules:
    - net.bytebuddy:byte-buddy-agent:1.7.9
    - net.bytebuddy:byte-buddy-agent:1.7.5
  A conflict was found between the following modules:
    - org.objenesis:objenesis:2.6
    - org.objenesis:objenesis:2.1

**Pull request merged**
