### PR TITLE
Issue #718: Remove blocking for reactor RetryOperator.

### PR DESCRIPTION
**Pull request by alex-pumpkin**
I can't fix it without changing `io.github.resilience4j.retry.Retry.Context` API. So backward compatibility is broken.

### CODE REVIEW

**Comment by RobWin** [comment]
Thank you. I take a look at it

**Comment by RobWin** [comment]
Couldn't we use `Retry.AsyncContext` in `RetryOperator.Context` instead of adapting `Retry.Context`.
The `Retry.AsyncContext` already has methods with return the delay in milliseconds.

```
public class RetryOperator<T> implements UnaryOperator<Publisher<T>> {

    private final Retry retry;

    private RetryOperator(Retry retry) {
        this.retry = retry;
    }

    /**
     * Creates a retry.
     *
     * @param <T>   the value type of the upstream and downstream
     * @param retry the retry
     * @return a RetryOperator
     */
    public static <T> RetryOperator<T> of(Retry retry) {
        return new RetryOperator<>(retry);
    }

    /**
     * to handle checked exception handling in reactor Function java 8 doOnNext
     */
    private static <T> Consumer<T> throwingConsumerWrapper(
        ThrowingConsumer<T, Exception> throwingConsumer) {

        return i -> {
            try {
                throwingConsumer.accept(i);
            } catch (Exception ex) {
                throw new RetryExceptionWrapper(ex);
            }
        };
    }

    public Publisher<T> apply(Publisher<T> publisher) {
        if (publisher instanceof Mono) {
            Context<T> context = new Context<>(retry.asyncContext());
            Mono<T> upstream = (Mono<T>) publisher;
            return upstream.doOnNext(context::handleResult)
                .retryWhen(errors -> errors.flatMap(context::handleErrors))
                .doOnSuccess(t -> context.onComplete());
        } else if (publisher instanceof Flux) {
            Context<T> context = new Context<>(retry.asyncContext());
            Flux<T> upstream = (Flux<T>) publisher;
            return upstream.doOnNext(context::handleResult)
                .retryWhen(errors -> errors.flatMap(context::handleErrors))
                .doOnComplete(context::onComplete);
        } else {
            throw new IllegalPublisherException(publisher);
        }
    }

    /**
     * @param <T> input
     * @param <E> possible thrown exception
     */
    @FunctionalInterface
    public interface ThrowingConsumer<T, E extends Exception> {

        void accept(T t) throws E;
    }

    private static class Context<T> {

        private final Retry.AsyncContext<T> retryContext;

        Context(Retry.AsyncContext<T> retryContext) {
            this.retryContext = retryContext;
        }

        void onComplete() {
            this.retryContext.onComplete();
        }

        void handleResult(T result) {
            long waitingDurationMillis = retryContext.onResult(result);
            if (waitingDurationMillis != -1) {
                throw new RetryDueToResultException(waitingDurationMillis);
            }
        }

        Mono<Long> handleErrors(Throwable throwable) {
            if (throwable instanceof RetryDueToResultException) {
                long waitDurationMillis = ((RetryDueToResultException) throwable).waitDurationMillis;
                return Mono.delay(Duration.ofMillis(waitDurationMillis));
            }
            // Filter Error to not retry on it
            if (throwable instanceof Error) {
                throw (Error) throwable;
            }

            long waitingDurationMillis = Try.of(() -> retryContext
                .onError(castToException(throwable)))
                .get();

            return Mono.delay(Duration.ofMillis(waitingDurationMillis));
        }

        private Exception castToException(Throwable throwable) {
            return throwable instanceof Exception ? (Exception) throwable
                : new Exception(throwable);
        }

        private static class RetryDueToResultException extends RuntimeException {
            private final long waitDurationMillis;

            RetryDueToResultException(long waitDurationMillis) {
                super("retry due to retryOnResult predicate");
                this.waitDurationMillis = waitDurationMillis;
            }
        }
    }
}
```

**Comment by alex-pumpkin** [comment]
Ok, I'll examine this approach

**Comment by alex-pumpkin** [comment]
Yes, it works with `AsyncContext` and `RetryOperator` changes.

**Comment by RobWin** [comment]
Very  nice

**Comment by RobWin** [comment]
I tried to apply it to RxJava2 as well, but I face some issues :(

```
public class RetryTransformer<T> implements FlowableTransformer<T, T>, ObservableTransformer<T, T>,
    SingleTransformer<T, T>, CompletableTransformer, MaybeTransformer<T, T> {

    private final Retry retry;

    private RetryTransformer(Retry retry) {
        this.retry = retry;
    }

    /**
     * Creates a RetryOperator.
     *
     * @param retry the Retry
     * @param <T>   the value type of the upstream and downstream
     * @return a RetryOperator
     */
    public static <T> RetryTransformer<T> of(Retry retry) {
        return new RetryTransformer<>(retry);
    }

    @Override
    public Publisher<T> apply(Flowable<T> upstream) {
        Context<T> context = new Context<>(retry.asyncContext());
        return upstream.doOnNext(context::handleResult)
            .retryWhen(errors -> errors.flatMap(context::handleFlowableErrors))
            .doOnComplete(context::onComplete);
    }

    @Override
    public ObservableSource<T> apply(Observable<T> upstream) {
        Context<T> context = new Context<>(retry.asyncContext());
        return upstream.doOnNext(context::handleResult)
            .retryWhen(errors -> errors.flatMap(context::handleObservableErrors))
            .doOnComplete(context::onComplete);
    }

    @Override
    public SingleSource<T> apply(Single<T> upstream) {
        Context<T> context = new Context<>(retry.asyncContext());
        return upstream.doOnSuccess(context::handleResult)
            .retryWhen(errors -> errors.flatMap(context::handleFlowableErrors))
            .doOnSuccess(t -> context.onComplete());
    }

    @Override
    public CompletableSource apply(Completable upstream) {
        Context<T> context = new Context<>(retry.asyncContext());
        return upstream.retryWhen(errors -> errors.flatMap(context::handleFlowableErrors))
            .doOnComplete(context::onComplete);
    }

    @Override
    public MaybeSource<T> apply(Maybe<T> upstream) {
        Context<T> context = new Context<>(retry.asyncContext());
        return upstream.doOnSuccess(context::handleResult)
            .retryWhen(errors -> errors.flatMap(context::handleFlowableErrors))
            .doOnSuccess(t -> context.onComplete())
            .doOnComplete(context::onComplete);
    }

    private static class Context<T> {

        private final Retry.AsyncContext<T> retryContext;

        Context(Retry.AsyncContext<T> retryContext) {
            this.retryContext = retryContext;
        }

        void onComplete() {
            this.retryContext.onComplete();
        }

        void handleResult(T result) {
            long waitDurationMillis = retryContext.onResult(result);
            if (waitDurationMillis != -1) {
                throw new RetryDueToResultException(waitDurationMillis);
            }
        }

        Publisher<Long> handleFlowableErrors(Throwable throwable) {
            if (throwable instanceof RetryDueToResultException) {
                long waitDurationMillis = ((RetryDueToResultException) throwable).waitDurationMillis;
                return Flowable.timer(waitDurationMillis, TimeUnit.MILLISECONDS);
            }
            // Filter Error to not retry on it
            if (throwable instanceof Error) {
                throw (Error) throwable;
            }

            long waitDurationMillis = retryContext.onError(throwable);

            if (waitDurationMillis == -1) {
                return Flowable.error(throwable);
            }

            return Flowable.timer(waitDurationMillis, TimeUnit.MILLISECONDS);
        }

        ObservableSource<Long> handleObservableErrors(Throwable throwable) {
            if (throwable instanceof RetryDueToResultException) {
                long waitDurationMillis = ((RetryDueToResultException) throwable).waitDurationMillis;
                return Observable.timer(waitDurationMillis, TimeUnit.MILLISECONDS);
            }
            // Filter Error to not retry on it
            if (throwable instanceof Error) {
                throw (Error) throwable;
            }

            long waitDurationMillis = retryContext.onError(throwable);

            if (waitDurationMillis == -1) {
                return Observable.error(throwable);
            }

            return Observable.timer(waitDurationMillis, TimeUnit.MILLISECONDS);
        }

        private static class RetryDueToResultException extends RuntimeException {
            private final long waitDurationMillis;

            RetryDueToResultException(long waitDurationMillis) {
                super("retry due to retryOnResult predicate");
                this.waitDurationMillis = waitDurationMillis;
            }
        }
    }
}
```

**Comment by RobWin** [comment]
Very strange. it seems `return Observable.timer(waitDurationMillis, TimeUnit.MILLISECONDS)` seems to be the issue. When I replace it by ` eturn Flowable.just(waitDurationMillis);` the retry works, but does not wait in between.
I hope it's not a bug in Rxjava2.

**Comment by RobWin** [comment]
Sometimes it's too obvious. The RxJava2 tests are bot waiting asynchronously for the terminal events.

**Pull request merged**
