### PR TITLE
Tests speedup - flaky acquirePermissionAndMetrics fixup (#617)

### PR DESCRIPTION
**Pull request by hexmind**
```
io.github.resilience4j.ratelimiter.internal.SemaphoreBasedRateLimiterImplTest > acquirePermissionAndMetrics FAILED

    com.jayway.awaitility.core.ConditionTimeoutException at SemaphoreBasedRateLimiterImplTest.java:147
```

### CODE REVIEW

**Comment by hexmind** [comment]
@storozhukBM

**Comment by RobWin** [comment]
Thx,
@storozhukBM changed the timeout to 50ms in his last commit. 

Why do you think does this change help?

**Comment by hexmind** [comment]
Previously it was `Duration.ofSeconds(5)`. He decreased it for speed, but 50ms is sometimes not enough (https://travis-ci.org/resilience4j/resilience4j/builds/586211955).
I have run test repeated n times and 100ms looks good enough (no failures).

**Comment by RobWin** [comment]
Ok, fine for me.

**Pull request merged**
