### PR TITLE
resilience4j-rxjava2: corrected compilation error in RetryTransformer.java

### PR DESCRIPTION
**Pull request by pvillela**
Corrected compilation error in RetryTransformer.java in resilience4j-rxjava2 caused by calls to SubscriptionArbiter.  In addition, refined onError implementation to avoid catching fatal errors.

### CODE REVIEW

**Comment by Romeh** [comment]
@pvillela can u please check why build is failing with compilation error of SubscriptionArbiter?

**Comment by RobWin** [comment]
It's the RxJava2 version. I guess it must be updated to `rxJavaVersion = '2.2.7`.
Seems the constructor changed.

**Comment by RobWin** [comment]
There is another PR which updates the RxJava2  version and modifies the same class.
https://github.com/resilience4j/resilience4j/pull/356

**Comment by Romeh** [comment]
@RobWin  I guess we can cancel this one as it is already covered in https://github.com/resilience4j/resilience4j/pull/356 , right ?

**Comment by RobWin** [comment]
I close this PR.
@Romeh will create a new one.

**Comment by Romeh** [comment]
created ! : https://github.com/resilience4j/resilience4j/pull/372

**Pull request closed without merging**
