### PR TITLE
 Fix invalid format of Endpoint ID

### LINKED ISSUE #1201: Actuator endpoint Id Invalid format
Resilience4j version: 1.6.0

Java version: 11

```
2020-10-12 16:30:11.654  WARN 96775 --- [           main] o.s.boot.actuate.endpoint.EndpointId     : Endpoint ID 'stream-circuitbreaker-events' contains invalid characters, please migrate to a valid format.
2020-10-12 16:30:11.655  WARN 96775 --- [           main] o.s.boot.actuate.endpoint.EndpointId     : Endpoint ID 'hystrix-stream-circuitbreaker-events' contains invalid characters, please migrate to a valid format.
```

spring boot is emitting warning message with resilience4j 1.6.0 because of Endpoint ID.

### PR DESCRIPTION
**Pull request by dlsrb6342**
* Resolves #1201

### CODE REVIEW

**Comment by Romeh** [comment]
@dlsrb6342  no documentation update is needed for that ?

**Review by Romeh — APPROVED** [review]

**Comment by hexmind** [comment]
It's a breaking change. Shouldn't be merge to 2.0 branch?

**Comment by dlsrb6342** [comment]
@Romeh 
Didn't added any docs about these endpoints. I'll request to contributor who added these. 

@hexmind 
Agree. @RobWin  what do you think?

**Comment by RobWin** [comment]
I think the endpoints have been added in this 1.6.0 release. I think we can still provide a hotfix release to fix the endpoint IDs.

**Comment by patpatpat123** [comment]
Hello,

Looking forward to it.
Many thanks for the fix.

**Comment by sanha** [comment]
@dlsrb6342 @RobWin 
Hi there :)

It seems that this patch is not applied to your v1.6.1 release.
[This](https://github.com/resilience4j/resilience4j/blob/v1.6.1/resilience4j-spring-boot2/src/main/java/io/github/resilience4j/circuitbreaker/monitoring/endpoint/CircuitBreakerHystrixServerSideEvent.java#L51) is the `CircuitBreakerHystrixServerSideEvent.java` file that you've released and the endpoint is still have hyphens.

**Comment by dlsrb6342** [comment]
@sanha 
Yes. This is not released yet. 
This will be included in next release.

**Comment by sanha** [comment]
@dlsrb6342 
Oh, I got it. This commit is not included in v1.6.1 even though v1.6.1 is released later than this commit.
I saw this commit is included in [the release note branch](https://github.com/resilience4j/resilience4j/commits/releasenotes-1.6.1) of v1.6.1 (but this may not be the official release note).

Thanks for your explanation :)

**Comment by patpatpat123** [comment]
Just asking, what would be the target version (and a possible ETA, pushing my luck)

Many thanks for the fix

**Comment by sbilello** [comment]
When will it be released?

**Pull request merged**
