### PR TITLE
[Performance] Improve circuitbreaker throughput

### PR DESCRIPTION
**Pull request by LinShunKang**
Hi, I did some minor performance optimizations for CircuitBreaker, you can see [here](https://github.com/resilience4j/resilience4j/issues/1391)

### CODE REVIEW

**Comment by RobWin** [comment]
Thanks,
would you also like to optimze `publishCircuitErrorEvent`?

**Comment by LinShunKang** [comment]
@RobWin 
I have optimized `CircuitBreakerStateMachine#publishCircuitErrorEvent` and made a simple refactoring, PTAL.

**Comment by LinShunKang** [comment]
@RobWin 
And, I found that `EventProcessor#processEvent(E)` has a performance problem: `Class#getSimpleName()` will always call `String#substring(int)` to generate simpleName, which will consume a lot of CPU and memory resources.

https://github.com/resilience4j/resilience4j/blob/08645507a35c8f1e319e6da0d1b80c7d016dfe8e/resilience4j-core/src/main/java/io/github/resilience4j/core/EventProcessor.java#L54-L69

**Review by RobWin — APPROVED** [review]

**Comment by RobWin** [comment]
Would you like to create an other improvment PR for `Class#getSimpleName()`.
What's your proposal?

**Comment by adwsingh** [comment]
`Class#getSimpleName()` is [cached in Java 11](https://bugs.openjdk.java.net/browse/JDK-8187123) as well as in certain distributions of Java 8, [like Coretto](https://github.com/corretto/corretto-8/blob/develop/src/jdk/src/share/classes/java/lang/Class.java#L1305-L1311).

**Comment by LinShunKang** [comment]
> Would you like to create an other improvment PR for `Class#getSimpleName()`.
> What's your proposal?

I have 3 proposals:
* Do nothing, just as @adwsingh  said, Java 11 has cached the value of simpleName
* Use `Class#getName()` instead.
* There is a fastest way i know, use `eventTypeId` to get `eventConsumerList`:
    * Add Interface `Event`:
        
        ```
        public interface Event {
        
            int getEventTypeId();
        }
        ```
    
    * Add Class `EventIdGenerator`:
        
        ```
        public final class EventIdGenerator {
        
            public static final int MAX_EVENT_ID = 4096;
        
            private static final AtomicInteger ID_IDX = new AtomicInteger(0);
        
            public static int nextId() {
                final int eventId = ID_IDX.incrementAndGet();
                if (eventId >= MAX_EVENT_ID) {
                    throw new IllegalStateException("eventId exceed MAX_EVENT_ID[" + MAX_EVENT_ID + "]");
                }
                return eventId;
            }
        
            private EventIdGenerator() {
                //empty
            }
        }
      ```
    
    * Let `CircuitBreakerEvent` extend `Event`, and `Type` add `id` field:
    
        ```
        public interface CircuitBreakerEvent extends Event {
        
            String getCircuitBreakerName();
        
            Type getEventType();
        
            ZonedDateTime getCreationTime();
        
            enum Type {
                ERROR(false),
                IGNORED_ERROR(false),
                SUCCESS(false),
                NOT_PERMITTED(false),
                STATE_TRANSITION(true),
                RESET(true),
                FORCED_OPEN(false),
                DISABLED(false),
                FAILURE_RATE_EXCEEDED(false),
                SLOW_CALL_RATE_EXCEEDED(false);
        
                public final boolean forcePublish;

                //Here is the key point        
                public final int id;
        
                Type(boolean forcePublish) {
                    this.forcePublish = forcePublish;
                    this.id = EventIdGenerator.nextId();
                }
            }
        }
        ```
        
    * Let `AbstractCircuitBreakerEvent` implement `getEventTypeId` method:

        ```
        abstract class AbstractCircuitBreakerEvent implements CircuitBreakerEvent {
        
            //Immutable and thread-safe
            private static final Clock SYSTEM_CLOCK = Clock.systemDefaultZone();
        
            private final String circuitBreakerName;
            private final ZonedDateTime creationTime;
        
            AbstractCircuitBreakerEvent(String circuitBreakerName) {
                this.circuitBreakerName = circuitBreakerName;
                this.creationTime = ZonedDateTime.now(SYSTEM_CLOCK);
            }
        
            @Override
            public int getEventTypeId() {
                return getEventType().id;
            }
        
            @Override
            public String getCircuitBreakerName() {
                return circuitBreakerName;
            }
        
            @Override
            public ZonedDateTime getCreationTime() {
                return creationTime;
            }
        }
        
        ```
        
    
    * Modify `EventProcessor`, use `eventTypeId` to get `consumerList`:

        ```
        public class EventProcessor<T extends Event> implements EventPublisher<T> {
        
            final List<EventConsumer<T>> onEventConsumers = new CopyOnWriteArrayList<>();
        
            //Here is the key point
            final AtomicReferenceArray<List<EventConsumer<T>>> eventConsumers = new AtomicReferenceArray<>(MAX_EVENT_ID);
        
            private boolean consumerRegistered;
        
            public boolean hasConsumers() {
                return consumerRegistered;
            }
        
            @SuppressWarnings("unchecked")
            public synchronized void registerConsumer(int eventTypeId, EventConsumer<? extends T> eventConsumer) {
                List<EventConsumer<T>> consumerList = this.eventConsumers.get(eventTypeId);
                if (consumerList == null) {
                    consumerList = new CopyOnWriteArrayList<>();
                    eventConsumers.set(eventTypeId, consumerList);
                }
        
                consumerList.add((EventConsumer<T>) eventConsumer);
                this.consumerRegistered = true;
            }
        
            public <E extends T> boolean processEvent(E event) {
                boolean consumed = false;
                if (!onEventConsumers.isEmpty()) {
                    onEventConsumers.forEach(onEventConsumer -> onEventConsumer.consumeEvent(event));
                    consumed = true;
                }
        
                //Here is the key point
                List<EventConsumer<T>> consumerList = this.eventConsumers.get(event.getEventTypeId());
                if (consumerList != null && !consumerList.isEmpty()) {
                    consumerList.forEach(consumer -> consumer.consumeEvent(event));
                    consumed = true;
                }
                return consumed;
            }
        
            @Override
            public synchronized void onEvent(@Nullable EventConsumer<T> onEventConsumer) {
                this.onEventConsumers.add(onEventConsumer);
                this.consumerRegistered = true;
           }
       }
       ```
       
       * Finally, modify `CircuitBreakerEventProcessor`:
       
        ```
           private class CircuitBreakerEventProcessor extends
                EventProcessor<CircuitBreakerEvent> implements EventConsumer<CircuitBreakerEvent>,
                EventPublisher {
        
                @Override
                public EventPublisher onSuccess(EventConsumer<CircuitBreakerOnSuccessEvent> onSuccessEventConsumer) {
                    registerConsumer(CircuitBreakerEvent.Type.SUCCESS.id, onSuccessEventConsumer);
                    return this;
                }
            }
        ```

**Comment by RobWin** [comment]
If `Class#getName()` is faster than `Class#getSimpleName()`, I would prefer this solution.

**Comment by LinShunKang** [comment]
> If `Class#getName()` is faster than `Class#getSimpleName()`, I would prefer this solution.

@RobWin 
Hi, I have submitted a [PR](https://github.com/resilience4j/resilience4j/pull/1400), please take a look.

**Comment by LinShunKang** [comment]
> If `Class#getName()` is faster than `Class#getSimpleName()`, I would prefer this solution.

I also compared using `eventTypeId` and `Class#getName()` to get eventConsumerList:
* Using `Class#getName()`:
```
Benchmark                                                                                    Mode  Cnt     Score    Error   Units
CircuitBreakerBenchmark.directSupplier                                                      thrpt   20    12.258 ±  0.019  ops/us
CircuitBreakerBenchmark.directSupplier:·gc.alloc.rate                                       thrpt   20    ≈ 10⁻⁴           MB/sec
CircuitBreakerBenchmark.directSupplier:·gc.alloc.rate.norm                                  thrpt   20    ≈ 10⁻⁵             B/op
CircuitBreakerBenchmark.directSupplier:·gc.count                                            thrpt   20       ≈ 0           counts
CircuitBreakerBenchmark.protectedSupplier                                                   thrpt   20     4.122 ±  0.033  ops/us
CircuitBreakerBenchmark.protectedSupplier:·gc.alloc.rate                                    thrpt   20  1017.650 ±  8.294  MB/sec
CircuitBreakerBenchmark.protectedSupplier:·gc.alloc.rate.norm                               thrpt   20   272.000 ±  0.001    B/op
CircuitBreakerBenchmark.protectedSupplier:·gc.churn.PS_Eden_Space                           thrpt   20  1019.431 ±  8.512  MB/sec
CircuitBreakerBenchmark.protectedSupplier:·gc.churn.PS_Eden_Space.norm                      thrpt   20   272.476 ±  0.609    B/op
CircuitBreakerBenchmark.protectedSupplier:·gc.churn.PS_Survivor_Space                       thrpt   20     0.162 ±  0.015  MB/sec
CircuitBreakerBenchmark.protectedSupplier:·gc.churn.PS_Survivor_Space.norm                  thrpt   20     0.043 ±  0.004    B/op
CircuitBreakerBenchmark.protectedSupplier:·gc.count                                         thrpt   20  2871.000           counts
CircuitBreakerBenchmark.protectedSupplier:·gc.time                                          thrpt   20  1849.000               ms
CircuitBreakerBenchmark.protectedSupplierWithDiffConsumer                                   thrpt   20     3.970 ±  0.023  ops/us
CircuitBreakerBenchmark.protectedSupplierWithDiffConsumer:·gc.alloc.rate                    thrpt   20   894.224 ± 79.317  MB/sec
CircuitBreakerBenchmark.protectedSupplierWithDiffConsumer:·gc.alloc.rate.norm               thrpt   20   248.000 ± 21.382    B/op
CircuitBreakerBenchmark.protectedSupplierWithDiffConsumer:·gc.churn.PS_Eden_Space           thrpt   20   896.456 ± 79.367  MB/sec
CircuitBreakerBenchmark.protectedSupplierWithDiffConsumer:·gc.churn.PS_Eden_Space.norm      thrpt   20   248.621 ± 21.406    B/op
CircuitBreakerBenchmark.protectedSupplierWithDiffConsumer:·gc.churn.PS_Survivor_Space       thrpt   20     0.159 ±  0.014  MB/sec
CircuitBreakerBenchmark.protectedSupplierWithDiffConsumer:·gc.churn.PS_Survivor_Space.norm  thrpt   20     0.044 ±  0.004    B/op
CircuitBreakerBenchmark.protectedSupplierWithDiffConsumer:·gc.count                         thrpt   20  2912.000           counts
CircuitBreakerBenchmark.protectedSupplierWithDiffConsumer:·gc.time                          thrpt   20  1821.000               ms
CircuitBreakerBenchmark.protectedSupplierWithOneConsumer                                    thrpt   20     4.021 ±  0.036  ops/us
CircuitBreakerBenchmark.protectedSupplierWithOneConsumer:·gc.alloc.rate                     thrpt   20  1037.001 ± 47.516  MB/sec
CircuitBreakerBenchmark.protectedSupplierWithOneConsumer:·gc.alloc.rate.norm                thrpt   20   284.000 ± 10.691    B/op
CircuitBreakerBenchmark.protectedSupplierWithOneConsumer:·gc.churn.PS_Eden_Space            thrpt   20  1038.596 ± 47.251  MB/sec
CircuitBreakerBenchmark.protectedSupplierWithOneConsumer:·gc.churn.PS_Eden_Space.norm       thrpt   20   284.439 ± 10.642    B/op
CircuitBreakerBenchmark.protectedSupplierWithOneConsumer:·gc.churn.PS_Survivor_Space        thrpt   20     0.168 ±  0.012  MB/sec
CircuitBreakerBenchmark.protectedSupplierWithOneConsumer:·gc.churn.PS_Survivor_Space.norm   thrpt   20     0.046 ±  0.003    B/op
CircuitBreakerBenchmark.protectedSupplierWithOneConsumer:·gc.count                          thrpt   20  2936.000           counts
CircuitBreakerBenchmark.protectedSupplierWithOneConsumer:·gc.time                           thrpt   20  1840.000               ms
```

* Using `eventTypeId`:
```
Benchmark                                                                                    Mode  Cnt     Score    Error   Units
CircuitBreakerBenchmark.directSupplier                                                      thrpt   20    12.247 ±  0.035  ops/us
CircuitBreakerBenchmark.directSupplier:·gc.alloc.rate                                       thrpt   20    ≈ 10⁻⁴           MB/sec
CircuitBreakerBenchmark.directSupplier:·gc.alloc.rate.norm                                  thrpt   20    ≈ 10⁻⁵             B/op
CircuitBreakerBenchmark.directSupplier:·gc.count                                            thrpt   20       ≈ 0           counts
CircuitBreakerBenchmark.protectedSupplier                                                   thrpt   20     5.657 ±  0.122  ops/us
CircuitBreakerBenchmark.protectedSupplier:·gc.alloc.rate                                    thrpt   20   246.478 ±  5.319  MB/sec
CircuitBreakerBenchmark.protectedSupplier:·gc.alloc.rate.norm                               thrpt   20    48.000 ±  0.001    B/op
CircuitBreakerBenchmark.protectedSupplier:·gc.churn.PS_Eden_Space                           thrpt   20   247.057 ±  5.173  MB/sec
CircuitBreakerBenchmark.protectedSupplier:·gc.churn.PS_Eden_Space.norm                      thrpt   20    48.114 ±  0.215    B/op
CircuitBreakerBenchmark.protectedSupplier:·gc.churn.PS_Survivor_Space                       thrpt   20     0.013 ±  0.005  MB/sec
CircuitBreakerBenchmark.protectedSupplier:·gc.churn.PS_Survivor_Space.norm                  thrpt   20     0.003 ±  0.001    B/op
CircuitBreakerBenchmark.protectedSupplier:·gc.count                                         thrpt   20  1267.000           counts
CircuitBreakerBenchmark.protectedSupplier:·gc.time                                          thrpt   20   800.000               ms
CircuitBreakerBenchmark.protectedSupplierWithDiffConsumer                                   thrpt   20     4.383 ±  0.021  ops/us
CircuitBreakerBenchmark.protectedSupplierWithDiffConsumer:·gc.alloc.rate                    thrpt   20   668.434 ± 85.155  MB/sec
CircuitBreakerBenchmark.protectedSupplierWithDiffConsumer:·gc.alloc.rate.norm               thrpt   20   168.000 ± 21.382    B/op
CircuitBreakerBenchmark.protectedSupplierWithDiffConsumer:·gc.churn.PS_Eden_Space           thrpt   20   669.752 ± 85.427  MB/sec
CircuitBreakerBenchmark.protectedSupplierWithDiffConsumer:·gc.churn.PS_Eden_Space.norm      thrpt   20   168.332 ± 21.454    B/op
CircuitBreakerBenchmark.protectedSupplierWithDiffConsumer:·gc.churn.PS_Survivor_Space       thrpt   20     0.163 ±  0.015  MB/sec
CircuitBreakerBenchmark.protectedSupplierWithDiffConsumer:·gc.churn.PS_Survivor_Space.norm  thrpt   20     0.041 ±  0.004    B/op
CircuitBreakerBenchmark.protectedSupplierWithDiffConsumer:·gc.count                         thrpt   20  2864.000           counts
CircuitBreakerBenchmark.protectedSupplierWithDiffConsumer:·gc.time                          thrpt   20  1831.000               ms
CircuitBreakerBenchmark.protectedSupplierWithOneConsumer                                    thrpt   20     4.333 ±  0.033  ops/us
CircuitBreakerBenchmark.protectedSupplierWithOneConsumer:·gc.alloc.rate                     thrpt   20   755.442 ±  5.800  MB/sec
CircuitBreakerBenchmark.protectedSupplierWithOneConsumer:·gc.alloc.rate.norm                thrpt   20   192.000 ±  0.001    B/op
CircuitBreakerBenchmark.protectedSupplierWithOneConsumer:·gc.churn.PS_Eden_Space            thrpt   20   756.851 ±  6.603  MB/sec
CircuitBreakerBenchmark.protectedSupplierWithOneConsumer:·gc.churn.PS_Eden_Space.norm       thrpt   20   192.357 ±  0.550    B/op
CircuitBreakerBenchmark.protectedSupplierWithOneConsumer:·gc.churn.PS_Survivor_Space        thrpt   20     0.168 ±  0.014  MB/sec
CircuitBreakerBenchmark.protectedSupplierWithOneConsumer:·gc.churn.PS_Survivor_Space.norm   thrpt   20     0.043 ±  0.004    B/op
CircuitBreakerBenchmark.protectedSupplierWithOneConsumer:·gc.count                          thrpt   20  2832.000           counts
CircuitBreakerBenchmark.protectedSupplierWithOneConsumer:·gc.time                           thrpt   20  1824.000               ms
```

**Pull request merged**
