### PR TITLE
Issue#887 merging the divided packages between spring boot 2 and spri…

### PR DESCRIPTION
**Pull request by Romeh**
merging spring boot and spring boot common , i will create another PR after this one for spring cloud common as well

### CODE REVIEW

**Comment by dlsrb6342** [comment]
I think we need to add `resilience4j-spring-boot-common` to resilience4j-deprecated repository.

**Comment by RobWin** [comment]
Yes indees

**Comment by RobWin** [comment]
@Romeh Could you also copy `resilience4j-spring-boot-common` into the other repo?

**Comment by Romeh** [comment]
> @Romeh Could you also copy `resilience4j-spring-boot-common` into the other repo?

added now https://github.com/resilience4j/resilience4j-deprecated

**Comment by dlsrb6342** [comment]
I thought we can move all `Abstract**ConfigurationOnMissingBean` logic to `**ConConfigurationOnMissingBean` or `**AutoConfiguration` 
What do you think about this?

**Comment by RobWin** [comment]
We can do it in a separate PR

**Pull request merged**
