### PR TITLE
Add .editorconfig

### PR DESCRIPTION
**Pull request by Stupremee**
- Add a .editorconfig file
- Format every file with the Twitter Styleguide rules

An editorconfig file was request in #627

### CODE REVIEW

**Comment by RobWin** [comment]
Compilation of the tests failed unfortunately.

```
home/travis/build/resilience4j/resilience4j/resilience4j-core/src/test/java/io/github/resilience4j/core/StringUtilsTest.java:9: error: cannot find symbol
        assertThat(StringUtils.isNotEmpty("bla")).isEqualTo(true);
```

**Comment by RobWin** [comment]
AAAAh, this PR is difficult. Whenver we merge some other PR, there is a merge conflict. 
Can you rebase one last time, I will directly merge it afterwards.

**Comment by Stupremee** [comment]
I have no idea why every commit exists two times now, but it can be merged

**Comment by worldtiki** [comment]
Just noticed that this change also committed .idea specific files.

The codeStyleConfig.xml is managed by the editor and after this change it clashes with my configs (and I'm sure many other folks). Intellij automatically adds this line:
`<option name="USE_PER_PROJECT_SETTINGS" value="true" />`.

If I revert it, it will just put it back. This makes it hard to work with this project. Simple things like switching branch are no longer possible because of these local changes.

**Comment by RobWin** [comment]
What is your suggestion? I think we should remove the .idea specific files again.

**Comment by worldtiki** [comment]
> What is your suggestion? I think we should remove the .idea specific files again.

I agree. But maybe someone else can comment on this or suggest an alternative.

**Comment by dlsrb6342** [comment]
I think we can do this as spring-cloud did. 
https://github.com/spring-cloud/spring-cloud-build#intellij-idea
Manage xml files in another directory not .idea and Add intelliJ setup guide on README.md or CONTRIBUTING.md

**Comment by RobWin** [comment]
Good idea

**Comment by hexmind** [comment]
Maybe we can also move more settings from xml to .editorconfig?
> Generic IntelliJ IDEA options that have the ij_ prefix and are applicable to all languages
https://blog.jetbrains.com/idea/2019/06/managing-code-style-on-a-directory-level-with-editorconfig/

**Comment by worldtiki** [comment]
My 2 cents. I like @hexmind's suggestion and the "batteries included" approach.
It's really cool if folks can just clone the project and get on with things rather than following extra manual steps, even if that has a small cost of this approach not being able to define every formatting rule.

**Comment by dlsrb6342** [comment]
I think we have to put all formatting rules.  
we will add checkstyle plugin(#628) and check rules in PR. So if we don't put all rules, contributors have to reformat their code after PR submitted. 
So I think we need to provide configs so that they can check formatting rules in their local env.

**Pull request merged**
