### PR TITLE
Missing property for writable stack trace in bulk config properties

### PR DESCRIPTION
**Pull request by worldtiki**
Missing property for writable stack trace in bulk config properties

### CODE REVIEW

**Comment by RobWin** [comment]
Thx. Could you please add a small test?

**Comment by Romeh** [comment]
Sorry for my late request , can u please extend spring boot 2 integration test in resilience4j spring boot 2 module by adding the new property there and assert it is loaded properly ? in https://github.com/resilience4j/resilience4j/blob/master/resilience4j-spring-boot2/src/test/resources/application.yaml#L119

**Comment by worldtiki** [comment]
> https://github.com/resilience4j/resilience4j/blob/master/resilience4j-spring-boot2/src/test/resources/application.yaml#L119

Sure :)

**Comment by RobWin** [comment]
thx

**Pull request merged**
