### PR TITLE
Grpc add on module

### PR DESCRIPTION
**Pull request by marcoferrer**
This PR introduces circuit breaker integration support for [grpc-java](https://github.com/grpc/grpc-java)

The PR is being opened as a draft since there are some discussions to be had about the API design. Tests and documentation also need to be completed.

These are the main APIs being introduced:
* `ChannelCircuitBreakerInterceptor`, Intercepts and records events for calls performed on the attach channel or stub. Im not particularly happy with the name. Its purpose is to apply the single provided circuit breaker indiscriminately to all calls.

```java

Channel channel = ClientInterceptors.intercept(
                injectedChannel, ChannelCircuitBreakerInterceptor.of(circuitBreaker));

SimpleServiceBlockingStub stub = SimpleServiceGrpc.newBlockingStub(channel);

SimpleServiceFutureStub stub2 = SimpleServiceGrpc.newFutureStub(channel);

Response response = stub.unaryRpc(request);

ListenableFuture<Response> responseFuture = stub.unaryRpc(request);

```

* `ClientCircuitBreakerInterceptor`, Interceptors all calls all calls performed on the attached channel or stub. If a circuit breaker is present within the call options then it will used for recording events. This interceptor allows users to dynamically configure what circuit breaker to use on a per call basis.
```java

SimpleServiceBlockingStub stub = SimpleServiceGrpc
                .newBlockingStub(channel);

Response response1 = stub.unaryRpc(request);

Response response2 = stub
                .withOption(CircuitBreakerCallOptions.CIRCUIT_BREAKER, circuitBreaker)
                .withOption(CircuitBreakerCallOptions.SUCCESS_STATUS,
                        status -> status.getCode() != Status.INVALID_ARGUMENT.getCode())
                .unaryRpc(request);

```

Ill add a description of the server interceptor API soon

### CODE REVIEW

**Comment by RobWin** [comment]
Hi @marcoferrer 
Could you please also create an issue and reference the PR.

**Comment by hexmind** [comment]
Could you please apply auto-format on classes created by you?

**Comment by marcoferrer** [comment]
@hexmind Are there any particular formatting rules I should have applied? Or are the IntelliJ defaults good enough?

**Comment by RobWin** [comment]
Maybe we should first merge the editorconfig PR. It should solve the issues in the future.

**Comment by marcoferrer** [comment]
Once it’s merged I’ll rebase and make sure to apply the formatting

**Comment by hexmind** [comment]
As was mentioned editorconfig is in progress. For now, IntelliJ default is better than none ;)

**Comment by RobWin** [comment]
Agree

**Comment by RobWin** [comment]
I would like to undestand why this gRPC module is needed.
The module is mainly needed to support the cancellation of calls, or?
Otherwise we could just decorate any method call on the `SimpleServiceBlockingStub` or `SimpleServiceFutureStub`. We of course have to add support to decorate a `ListenableFuture`. 
Can a `ListenableFuture` be cancelled?

**Comment by marcoferrer** [comment]
So there are two parts that this module would cover. The first I outlined above, and that was decoration of client calls. The second is the decoration of server method implementations. 

While you do bring up a good point about decorating blocking stubs and providing support for listenable future, those arent the only stub types provided by client generators for the jvm. This module would allow support for any client `AbstractStub` implementation. Also these solutions wouldnt handle cancellations well, which is a big loss for users who rely on it for releasing resources in service implementations.

One common use case we've experienced is adding a circuit breaker for all calls to a specific server. Explicitly decorating every call site throughout the codebase has proven error prone.

```java
Channel channel = ...; // Channel for my-api.com

SimpleServiceBlockingStub simpleStub = SimpleServiceGrpc.newBlockingStub(channel)

AnotherServiceBlockingStub anotherStub = SimpleServiceGrpc.newBlockingStub(channel)

Response simpleResult = circuitBreaker
    .executeSupplier(() -> simpleStub.unaryRpc(...));

Response simpleResult = circuitBreaker
    .executeSupplier(() -> anotherStub.unaryRpc(...));
```

Using an interceptor to decorate the channels used to instantiate client stubs simplifies things for users. 
```java
Channel channel = ClientInterceptors
    .intercept(actualChannel, ClientCircuitBreakerInterceptor.of(circuitBreaker)); // Channel for my-api.com

SimpleServiceBlockingStub simpleStub = SimpleServiceGrpc.newBlockingStub(channel)

AnotherServiceBlockingStub anotherStub = SimpleServiceGrpc.newBlockingStub(channel)

Response simpleResult = simpleStub.unaryRpc(...);

Response simpleResult = anotherStub.unaryRpc(...);
```

As for decorating services, again we would gain the benefit of properly handling client cancellations propagated to the server. It would also simplify service method decoration regardless of the type of implementation used. 

```
class SimpleService {

   public void unaryRpcManualDecoration(Request request, StreamObserver<Response> streamObserver){
        try{
            circuitBreaker.executeSupplier(() -> {
                 .......; // Service method impl
            });
        }catch(CallNotPermittedException exception){
           streamObserver.onError(Status.UNAVAILABLE
                   .withDescription(exception.getMessage()))
                   .withCause(exception)
                   .asRuntimeException())
        } 
   }

   public void unaryRpcInterceptorDecoration(Request request, StreamObserver<Response> streamObserver){
         .......; // Service method impl
   }
}

```

**Comment by RobWin** [comment]
Tha is for the detailed explanation

**Comment by RobWin** [comment]
When you think you are done, just request an review.

**Comment by kdombeck** [comment]
@marcoferrer is there any update on this PR? Do you need/want some help with it?

**Comment by kdombeck** [comment]
@RobWin since it appears that @marcoferrer has abandoned this PR I have created a branch in my [repo](https://github.com/kdombeck/resilience4j/tree/grpc-add-module) that has been merged with master. I have been testing it and it is working well. Please let me know how you would like me to proceed with getting this merge into this project. Example: should I open a new PR or something else. Thanks

**Comment by RobWin** [comment]
Hi, in general a new module is always nice to have, but we also need someone who wants to maintain it.
@kdombeck Would you join the team then?

**Comment by kdombeck** [comment]
> Hi, in general a new module is always nice to have, but we also need someone who wants to maintain it.
> @kdombeck Would you join the team then?

Can you tell me what the expectations are for joining the team? I am interested.

**Comment by RobWin** [comment]
You can join our Slack channel.
From time to time you can answer GitHub issues which are related to your module, contribute further bugfixes, enhancements or review PRs from others.

**Comment by kdombeck** [comment]
> You can join our Slack channel.
> Now and then you shoud answer GitHub issues which are related to your module, contribute further bugfixes, enhancements or review PRs from others.

I can do that. Sign me up.

**Comment by RobWin** [comment]
What's your email address?
Are you still interested?

**Comment by kdombeck** [comment]
> What's your email address?
> Are you still interested?

kdombeck @ gmail.com
Yes I'm still interested. I have been working on the unit tests to improve coverage.

**Comment by w20k** [comment]
Hi, 

Is there any update on this PR? :) 
I was looking for implementation of GRPC Server rate limiter and circuit breaker, but only found this PR (which is also great, thanks!); Or maybe someone could point me to a right direction, where would be the `best place` to insert the Rate Limiter?

Thanks!

**Comment by kdombeck** [comment]
> Hi,
> 
> Is there any update on this PR? :)
> I was looking for implementation of GRPC Server rate limiter and circuit breaker, but only found this PR (which is also great, thanks!); Or maybe someone could point me to a right direction, where would be the `best place` to insert the Rate Limiter?
> 
> Thanks!

I have been working on rate limiter and will hopefully have a PR soon.

**Comment by RobWin** [comment]
Closing in favor of #1459

**Pull request closed without merging**
