### PR TITLE
fixes #1619

### LINKED ISSUE #1619: Version io.github.resilience4j:resilience4j-all:1.7.1 Unable to resolve circuitbreaker, ratelimiter, or retry
Resilience4j version: 
**1.7.1**

Java version:
**openjdk version "1.8.0_312"
OpenJDK Runtime Environment (Temurin)(build 1.8.0_312-b07)
OpenJDK 64-Bit Server VM (Temurin)(build 25.312-b07, mixed mode)**

Attempting to use version `io.github.resilience4j:resilience4j-all:1.7.1` from `1.7.0`, Gradle build outputs the following errors: 

## Errors
```bash
error: package io.github.resilience4j.circuitbreaker does not exist
error: package io.github.resilience4j.ratelimiter does not exist
error: package io.github.resilience4j.retry does not exist
```

## File Imports
```java
import io.github.resilience4j.circuitbreaker.CircuitBreaker;
import io.github.resilience4j.circuitbreaker.CircuitBreakerConfig;
import io.github.resilience4j.circuitbreaker.CircuitBreakerRegistry;
import io.github.resilience4j.micrometer.tagged.TaggedCircuitBreakerMetrics;
import io.github.resilience4j.micrometer.tagged.TaggedRateLimiterMetrics;
import io.github.resilience4j.micrometer.tagged.TaggedRetryMetrics;
import io.github.resilience4j.ratelimiter.RateLimiter;
import io.github.resilience4j.ratelimiter.RateLimiterConfig;
import io.github.resilience4j.ratelimiter.RateLimiterRegistry;
import io.github.resilience4j.retry.Retry;
import io.github.resilience4j.retry.RetryConfig;
```

Using version `1.7.0` and lower does not exhibit the same behavior and in reviewing the release notes, I didn't see anything that would indicate that the `-all` does not contain the associated packages.

### PR DESCRIPTION
**Pull request by piyushmor**
fixes #1619

Signed-off-by: Piyush Mor <piyush.mor@gmail.com>

### CODE REVIEW

**Comment by piyushmor** [comment]
@RobWin can you please help with the build?

**Comment by RobWin** [comment]
Hi, could try to rebase your branch to the latest changes from master?

**Comment by piyushmor** [comment]
rebased, however some tests are failing when they should not, maybe re-triggering the build will help

**Comment by RobWin** [comment]
I have a look at it.
The test also fails on master since some days.

**Review by RobWin — APPROVED** [review]

**Comment by RobWin** [comment]
Sry, could you rebases the latest changes again?
Should fix the unit test.

**Comment by RobWin** [comment]
Perfect. Tank you

**Pull request merged**
