### PR TITLE
Fixed threadpool bulkhead spring

### PR DESCRIPTION
**Pull request by Romeh**
@RobWin Example from spring boot 2 test configuration for fixed thread pool bulkhead separate name space:

```
resilience4j.thread-pool-bulkhead":
  configs:
    default:
      threadPoolProperties:
        maxThreadPoolSize: 4
        coreThreadPoolSize: 2
        queueCapacity: 2
  backends:
    backendB:
      baseConfig: default
    backendC:
      threadPoolProperties:
        maxThreadPoolSize: 1
        coreThreadPoolSize: 1
        queueCapacity: 1
```

### CODE REVIEW

**Comment by Romeh** [comment]
found an issue with separate name space in DefaultEventConsumerRegistry , as now u can register the same backend name twice , one for semaphore and one for fixed thread pool which leads to override the string key name in the map of DefaultEventConsumerRegistry

**Comment by RobWin** [comment]
Mh, then let's add a prefix to the event consumer id.

**Comment by Romeh** [comment]
Done !

**Comment by Romeh** [comment]
@RobWin  should i rename backends to instances as it is new feature anyhow , so let us dot it right from the beginning or it will be confusing for the user ? i can maybe add it to the rest of spring support and deprecate backends to not break the backward compatibility

**Comment by RobWin** [comment]
We have a similar discussion in PR #460

**Comment by RobWin** [comment]
Let's do it in a separate PR

**Pull request merged**
