### PR TITLE
Jdk 11 support

### PR DESCRIPTION
**Pull request by RobWin**

### CODE REVIEW

**Comment by 123Haynes** [comment]
@RobWin you need to rebase this on top of the current master and change
`spockVersion = '1.3-RC1-groovy-2.4'`
to
`spockVersion = '1.3-groovy-2.5'`

after that that java 11 build should work 😃

**Comment by RobWin** [comment]
I try ;)

**Comment by 123Haynes** [comment]
@RobWin That worked 👍   
But the travis config seems to be a bit weird. Why are there 2 java 8 jobs in the test stage and one is failing while the other one is passing?

**Comment by RobWin** [comment]
Yes, I'm also reading TravisCI docs at the moment. I guess it's the default TravisCI test stage `gradlew check` which is running twice. And my defined test stage is running as a third job.

**Pull request merged**
